receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: "opentelemetry-collector"
          scrape_interval: 600s
          static_configs:
            - targets: ["127.0.0.1:8888"]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/ready"

processors:
  batch: {}
  groupbyattrs:
    keys:
      - fruit
  transform:
    error_mode: propagate
    log_statements:
    - context: log
      statements:
        - set(log.attributes["abcdefg"], "20250706-0817")
        # - set(resource.attributes["fruit"], attributes["fruit"])

exporters:
  otlphttp/logs:
    endpoint: http://127.0.0.1:3100/otlp
    tls:
      insecure: true
  debug/logs:
    verbosity: detailed
  debug/metrics:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [groupbyattrs, transform, batch]
      exporters: [otlphttp/logs]
      #exporters: [otlphttp/logs, debug/logs]
    metrics:
      receivers: [otlp, prometheus/collector]
      processors: [batch]
      #exporters: [otlphttp/metrics]
      exporters: [otlphttp/metrics,debug/metrics]